// SPDX-License-Identifier: LGPL-2.1-or-later

package enc

import (
	"math"
	"os"
	"testing"

	"github.com/tphakala/go-aac/internal/coder"
	"github.com/tphakala/go-aac/internal/tables"
)

// Fixture generated by tools/ctwoloop fix_stereo_tools: the whole non-NMR
// stereo tool chain in the order aac_encode_frame runs it (aacenc.c:1223-1255
// @ d09d5afc3a) - mark_pns, search_for_quantizers_twoloop, search_for_pns,
// ff_aac_search_for_is, apply_intensity_stereo, search_for_ms,
// apply_mid_side_stereo - on both EIGHT_SHORT window groups and long frames,
// from a -ffp-contract=off build.
//
// TestTwoLoopStereoAgainstC covers the same chain but only on long frames
// with PNS off, so it never sees a NOISE_BT band, never sees a window group,
// and never sees a band the quantizer zeroed. Those are exactly the inputs
// that decide differently rather than just rounding differently, so this
// fixture records every discrete output of the chain (can_pns, zeroes,
// max_sfb, band_type, sf_idx, is_mask, ms_mask) alongside the floats: a
// flipped decision fails here instead of hiding behind matching coefficients.

// tlstReader walks the fixture. Separate from tlsReader so the two fixture
// formats stay independently readable.
type tlstReader struct {
	buf []byte
	off int
}

func (f *tlstReader) i32() int {
	v := int32(uint32(f.buf[f.off]) | uint32(f.buf[f.off+1])<<8 |
		uint32(f.buf[f.off+2])<<16 | uint32(f.buf[f.off+3])<<24)
	f.off += 4
	return int(v)
}

func (f *tlstReader) f32bits() uint32 {
	v := uint32(f.buf[f.off]) | uint32(f.buf[f.off+1])<<8 |
		uint32(f.buf[f.off+2])<<16 | uint32(f.buf[f.off+3])<<24
	f.off += 4
	return v
}

func (f *tlstReader) boolean() bool {
	v := f.buf[f.off] != 0
	f.off++
	return v
}

// wantInts checks a 128-entry int field against the fixture.
func (f *tlstReader) wantInts(t *testing.T, got *[128]int, what string, ci int) {
	t.Helper()
	for i := range 128 {
		if w := f.i32(); got[i] != w {
			t.Fatalf("case %d: %s[%d] = %d, want %d", ci, what, i, got[i], w)
		}
	}
}

// wantBools checks a 128-entry bool field against the fixture.
func (f *tlstReader) wantBools(t *testing.T, got *[128]bool, what string, ci int) {
	t.Helper()
	for i := range 128 {
		if w := f.boolean(); got[i] != w {
			t.Fatalf("case %d: %s[%d] = %v, want %v", ci, what, i, got[i], w)
		}
	}
}

// wantFloats checks a 128-entry float32 field bit-exactly.
func (f *tlstReader) wantFloats(t *testing.T, got *[128]float32, what string, ci int) {
	t.Helper()
	for i := range 128 {
		if w := f.f32bits(); math.Float32bits(got[i]) != w {
			t.Fatalf("case %d: %s[%d] = %08x, want %08x", ci, what, i,
				math.Float32bits(got[i]), w)
		}
	}
}

// wantCoeffs checks all 1024 spectral coefficients bit-exactly.
func (f *tlstReader) wantCoeffs(t *testing.T, got *[1024]float32, what string, ci int) {
	t.Helper()
	for k := range 1024 {
		if w := f.f32bits(); math.Float32bits(got[k]) != w {
			t.Fatalf("case %d: %s[%d] = %08x, want %08x", ci, what, k,
				math.Float32bits(got[k]), w)
		}
	}
}

type stereoToolsCase struct {
	srIdx, rate, bitrate int
	short                bool
	bitresAlloc          int
	lambda               float32
	bandwidth            int
	amp, alpha, beta     float32
	thrRLo, thrRHi       float32
	sprLo, sprHi         float32
}

// stereoToolsCases mirrors the fix_stereo_tools call list in
// tools/ctwoloop/ctwoloop.c; the two must stay in step.
var stereoToolsCases = []stereoToolsCase{
	{4, 44100, 192000, true, -1, 410, 18900, 1.0, 0.90, 0.10, 0.02, 0.2, 1.2, 2.0},
	{4, 44100, 96000, true, 1200, 2600, 15000, 2.0, 0.97, 0.03, 0.05, 0.5, 1.0, 2.0},
	{3, 48000, 128000, false, -1, 120, 18000, 1.0, 0.95, 0.05, 0.002, 0.02, 0.6, 1.8},
	{4, 44100, 64000, false, -1, 900, 13000, 0.5, 0.80, 0.30, 0.03, 0.3, 0.9, 2.0},
	// Loud content, near-zero masking thresholds, starved rate: the only
	// combination that arms twoloop's "trade overdistorted bands for
	// PNS-able zeroes" branch, which converts a coded band into a PNS band.
	{4, 44100, 16000, true, -1, 410, 18900, 40, 0.90, 0.10, 1e-4, 8e-4, 1.2, 2.0},
	{4, 44100, 16000, false, -1, 410, 18900, 40, 0.90, 0.10, 1e-4, 8e-4, 1.2, 2.0},
}

// tlstBuild fills one CPE and its two psy band sets exactly the way
// fix_stereo_tools does, drawing from the shared LCG in the same order.
func tlstBuild(l *tlsLCG, tc *stereoToolsCase, cpe *coder.ChannelElement,
	psy *[2][128]coder.PsyBand) {
	for ch := range 2 {
		ics := &cpe.Ch[ch].ICS
		if tc.short {
			ics.WindowSequence[0] = coder.EightShortSequence
			ics.NumWindows = 8
			ics.GroupLen = [8]int{1, 3, 0, 0, 3, 0, 0, 1}
			ics.SwbSizes = tables.SwbSize128[tc.srIdx]
			ics.SwbOffset = tables.SwbOffset128[tc.srIdx]
			ics.NumSwb = int(tables.NumSwb128[tc.srIdx])
		} else {
			ics.WindowSequence[0] = coder.OnlyLongSequence
			ics.NumWindows = 1
			ics.GroupLen[0] = 1
			ics.SwbSizes = tables.SwbSize1024[tc.srIdx]
			ics.SwbOffset = tables.SwbOffset1024[tc.srIdx]
			ics.NumSwb = int(tables.NumSwb1024[tc.srIdx])
		}
		ics.MaxSfb = ics.NumSwb
	}
	cpe.CommonWindow = 1

	s0, s1 := &cpe.Ch[0], &cpe.Ch[1]
	tlsSynthFrame(l, s0, tc.amp)
	var n [1040]float32
	for i := range n {
		n[i] = 2.0*l.f() - 1.0
	}
	for k := range 1024 {
		a := float32(tc.alpha * s0.Coeffs[k]) // no cross-statement FMA
		b := float32(tc.beta * n[k])
		s1.Coeffs[k] = a + b
	}
	nw := s0.ICS.NumWindows
	hf := int(s0.ICS.SwbOffset[s0.ICS.NumSwb*2/3])
	for w := range nw {
		for k := hf; k < 1024/nw; k++ {
			s1.Coeffs[w*128+k] = 0.6 * s0.Coeffs[w*128+k]
		}
	}
	for ch := range 2 {
		sc := &cpe.Ch[ch]
		for w := range sc.ICS.NumWindows {
			for g := range sc.ICS.NumSwb {
				b := &psy[ch][w*16+g]
				a0, a1 := int(sc.ICS.SwbOffset[g]), int(sc.ICS.SwbOffset[g+1])
				e := float32(0.0)
				for k := a0; k < a1; k++ {
					t := float32(sc.Coeffs[w*128+k] * sc.Coeffs[w*128+k])
					e += t
				}
				b.Energy = e
				d := float32((tc.thrRHi - tc.thrRLo) * l.f()) // no FMA
				b.Threshold = e * (tc.thrRLo + d)
				d2 := float32((tc.sprHi - tc.sprLo) * l.f())
				b.Spread = tc.sprLo + d2
			}
		}
	}
}

// TestTwoLoopStereoToolsAgainstC replays the full non-NMR stereo tool chain,
// PNS included and over EIGHT_SHORT window groups, against the C.
func TestTwoLoopStereoToolsAgainstC(t *testing.T) {
	raw, err := os.ReadFile("testdata/twoloop_stereo_tools.bin")
	if err != nil {
		t.Fatal(err)
	}
	f := &tlstReader{buf: raw}
	lcg := tlsLCG(0x9e3779b9)
	var cd coder.Coder

	for ci := range stereoToolsCases {
		tc := &stereoToolsCases[ci]
		var cpe coder.ChannelElement
		var psy [2][128]coder.PsyBand
		tlstBuild(&lcg, tc, &cpe, &psy)
		s0, s1 := &cpe.Ch[0], &cpe.Ch[1]

		// mark_pns then the quantizer, per channel (aacenc.c:1221-1226)
		for ch := range 2 {
			sc := &cpe.Ch[ch]
			cd.MarkPNS(tc.rate, tc.bandwidth, sc, &psy[ch], tc.lambda)
			cd.SearchForQuantizersTwoLoop(tc.bitrate, tc.rate, 2, tc.bitresAlloc,
				tc.bandwidth, true, sc, &psy[ch], tc.lambda)
		}
		for ch := range 2 {
			sc := &cpe.Ch[ch]
			f.wantBools(t, &sc.CanPNS, "can_pns", ci)
			f.wantInts(t, &sc.SfIdx, "sf_idx", ci)
			f.wantInts(t, &sc.BandType, "band_type", ci)
			f.wantBools(t, &sc.Zeroes, "zeroes", ci)
			if w := f.i32(); sc.ICS.MaxSfb != w {
				t.Fatalf("case %d ch%d: max_sfb = %d, want %d", ci, ch, sc.ICS.MaxSfb, w)
			}
		}

		// PNS per channel, sharing one LFSR (aacenc.c:1228-1239)
		cd.RandomState = 0x1f2e3d4c
		for ch := range 2 {
			cd.SearchForPNS(tc.rate, tc.bandwidth, &cpe.Ch[ch], &psy[ch], tc.lambda)
		}
		if w := f.i32(); cd.RandomState != int32(w) {
			t.Fatalf("case %d: random_state = %08x, want %08x", ci,
				uint32(cd.RandomState), uint32(w))
		}
		for ch := range 2 {
			sc := &cpe.Ch[ch]
			f.wantInts(t, &sc.SfIdx, "post-pns sf_idx", ci)
			f.wantInts(t, &sc.BandType, "post-pns band_type", ci)
			f.wantBools(t, &sc.Zeroes, "post-pns zeroes", ci)
			f.wantFloats(t, &sc.PnsEner, "post-pns pns_ener", ci)
		}

		cd.SearchForIS(tc.rate, &cpe, &psy[0], &psy[1], tc.lambda)
		applyIntensityStereo(&cpe)

		if got, want := cpe.IsMode, f.boolean(); got != want {
			t.Fatalf("case %d: is_mode = %v, want %v", ci, got, want)
		}
		f.wantBools(t, &cpe.IsMask, "is_mask", ci)
		f.wantBools(t, &cpe.MsMask, "post-is ms_mask", ci)
		f.wantFloats(t, &s0.IsEner, "is_ener0", ci)
		f.wantFloats(t, &s1.IsEner, "is_ener1", ci)
		f.wantInts(t, &s1.BandType, "post-is band_type1", ci)
		f.wantCoeffs(t, &s0.Coeffs, "post-is coeffs0", ci)
		f.wantCoeffs(t, &s1.Coeffs, "post-is coeffs1", ci)

		cd.SearchForMS(&cpe, &psy[0], &psy[1], tc.lambda)
		applyMidSideStereo(&cpe)

		f.wantBools(t, &cpe.MsMask, "ms_mask", ci)
		f.wantInts(t, &s0.SfIdx, "post-ms sf_idx0", ci)
		f.wantInts(t, &s1.SfIdx, "post-ms sf_idx1", ci)
		f.wantInts(t, &s0.BandType, "post-ms band_type0", ci)
		f.wantInts(t, &s1.BandType, "post-ms band_type1", ci)
		f.wantBools(t, &s0.Zeroes, "post-ms zeroes0", ci)
		f.wantBools(t, &s1.Zeroes, "post-ms zeroes1", ci)
		f.wantCoeffs(t, &s0.Coeffs, "post-ms coeffs0", ci)
		f.wantCoeffs(t, &s1.Coeffs, "post-ms coeffs1", ci)
	}
	if f.off != len(f.buf) {
		t.Fatalf("fixture: %d bytes left", len(f.buf)-f.off)
	}
}
