// SPDX-License-Identifier: LGPL-2.1-or-later

package enc

import (
	"encoding/binary"
	"math"
	"os"
	"testing"

	"github.com/tphakala/go-aac/internal/coder"
	"github.com/tphakala/go-aac/internal/tables"
)

// Fixture generated by tools/ctwoloop fix_stereo: the real twoloop search
// per channel, then the non-NMR stereo order ff_aac_search_for_is,
// apply_intensity_stereo, search_for_ms, apply_mid_side_stereo
// (-ffp-contract=off build). The Go port must match bit-exactly.

type tlsLCG uint32

func (l *tlsLCG) next() uint32 {
	*l = tlsLCG(uint32(*l)*1664525 + 1013904223)
	return uint32(*l)
}

func (l *tlsLCG) f() float32 { return float32(l.next()>>8) / 16777216.0 }

type tlsReader struct {
	t   *testing.T
	buf []byte
	off int
}

func (f *tlsReader) i32() int32 {
	v := int32(binary.LittleEndian.Uint32(f.buf[f.off:]))
	f.off += 4
	return v
}

func (f *tlsReader) f32bits() uint32 {
	v := binary.LittleEndian.Uint32(f.buf[f.off:])
	f.off += 4
	return v
}

func (f *tlsReader) u8() uint8 {
	v := f.buf[f.off]
	f.off++
	return v
}

func tlsSynthFrame(l *tlsLCG, sce *coder.SingleChannelElement, amp float32) {
	var n [1040]float32
	for i := range n {
		n[i] = 2.0*l.f() - 1.0
	}
	ics := &sce.ICS
	for w := 0; w < ics.NumWindows; w += ics.GroupLen[w] {
		for g := range ics.NumSwb {
			profile := int(l.next() % 5)
			e := [5]float32{0.0, 0.02, 0.6, 4.0, 40.0}[profile]
			for w2 := range ics.GroupLen[w] {
				s0, s1 := int(ics.SwbOffset[g]), int(ics.SwbOffset[g+1])
				for k := s0; k < s1; k++ {
					acc := float32(0.0)
					for j := 0; j <= 3; j++ {
						acc += n[(w+w2)*128+k+j]
					}
					sce.Coeffs[(w+w2)*128+k] = amp * e * acc
				}
			}
		}
	}
}

//nolint:gocognit,gocyclo // sequential fixture-format walk
func TestTwoLoopStereoAgainstC(t *testing.T) {
	raw, err := os.ReadFile("testdata/twoloop_stereo.bin")
	if err != nil {
		t.Fatal(err)
	}
	f := &tlsReader{t: t, buf: raw}
	lcg := tlsLCG(0x243f6a88)
	var cd coder.Coder
	var psy [2][128]coder.PsyBand

	cases := []struct {
		srIdx, rate, bitrate int
		lambda, alpha, beta  float32
	}{
		{4, 44100, 128000, 120.0, 0.95, 0.05},
		{3, 48000, 96000, 260.0, 0.80, 0.30},
		{4, 44100, 192000, 70.0, 0.99, 0.01},
	}

	for ci, tc := range cases {
		var cpe coder.ChannelElement
		for ch := range 2 {
			sc := &cpe.Ch[ch]
			sc.ICS.WindowSequence[0] = coder.OnlyLongSequence
			sc.ICS.NumWindows = 1
			sc.ICS.GroupLen[0] = 1
			sc.ICS.SwbSizes = tables.SwbSize1024[tc.srIdx]
			sc.ICS.SwbOffset = tables.SwbOffset1024[tc.srIdx]
			sc.ICS.NumSwb = int(tables.NumSwb1024[tc.srIdx])
			sc.ICS.MaxSfb = sc.ICS.NumSwb
		}
		cpe.CommonWindow = 1
		s0, s1 := &cpe.Ch[0], &cpe.Ch[1]
		bandwidth := min(tc.rate/2, 20000)

		tlsSynthFrame(&lcg, s0, 1.0)
		var n [1040]float32
		for i := range n {
			n[i] = 2.0*lcg.f() - 1.0
		}
		for k := range 1024 {
			a := float32(tc.alpha * s0.Coeffs[k]) // no cross-statement FMA
			b := float32(tc.beta * n[k])
			s1.Coeffs[k] = a + b
		}
		hf := int(s0.ICS.SwbOffset[30])
		for k := hf; k < 1024; k++ {
			s1.Coeffs[k] = 0.6 * s0.Coeffs[k]
		}
		for ch := range 2 {
			sc := &cpe.Ch[ch]
			for g := range sc.ICS.NumSwb {
				b := &psy[ch][g]
				a0, a1 := int(sc.ICS.SwbOffset[g]), int(sc.ICS.SwbOffset[g+1])
				e := float32(0.0)
				for k := a0; k < a1; k++ {
					t := float32(sc.Coeffs[k] * sc.Coeffs[k])
					e += t
				}
				b.Energy = e
				d := float32(0.02 * lcg.f()) // no FMA
				b.Threshold = e * (0.002 + d)
				d2 := float32(1.2 * lcg.f())
				b.Spread = 0.6 + d2
			}
		}

		cd.SearchForQuantizersTwoLoop(tc.bitrate, tc.rate, 2, -1, bandwidth,
			false, s0, &psy[0], tc.lambda)
		cd.SearchForQuantizersTwoLoop(tc.bitrate, tc.rate, 2, -1, bandwidth,
			false, s1, &psy[1], tc.lambda)

		cd.SearchForIS(tc.rate, &cpe, &psy[0], &psy[1], tc.lambda)
		applyIntensityStereo(&cpe)

		if got, want := cpe.IsMode, f.u8() != 0; got != want {
			t.Fatalf("case %d: is_mode = %v, want %v", ci, got, want)
		}
		for i := range 128 {
			if got, want := cpe.IsMask[i], f.u8() != 0; got != want {
				t.Fatalf("case %d: is_mask[%d] = %v, want %v", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := math.Float32bits(s0.IsEner[i]), f.f32bits(); got != want {
				t.Fatalf("case %d: is_ener0[%d] = %x, want %x", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := math.Float32bits(s1.IsEner[i]), f.f32bits(); got != want {
				t.Fatalf("case %d: is_ener1[%d] = %x, want %x", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := s1.BandType[i], int(f.i32()); got != want {
				t.Fatalf("case %d: band_type1[%d] = %d, want %d", ci, i, got, want)
			}
		}
		for k := range 1024 {
			if got, want := math.Float32bits(s0.Coeffs[k]), f.f32bits(); got != want {
				t.Fatalf("case %d post-IS: coeffs0[%d] = %x, want %x", ci, k, got, want)
			}
		}
		for k := range 1024 {
			if got, want := math.Float32bits(s1.Coeffs[k]), f.f32bits(); got != want {
				t.Fatalf("case %d post-IS: coeffs1[%d] = %x, want %x", ci, k, got, want)
			}
		}

		cd.SearchForMS(&cpe, &psy[0], &psy[1], tc.lambda)
		applyMidSideStereo(&cpe)

		for i := range 128 {
			if got, want := cpe.MsMask[i], f.u8() != 0; got != want {
				t.Fatalf("case %d: ms_mask[%d] = %v, want %v", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := s0.SfIdx[i], int(f.i32()); got != want {
				t.Fatalf("case %d: sf_idx0[%d] = %d, want %d", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := s1.SfIdx[i], int(f.i32()); got != want {
				t.Fatalf("case %d: sf_idx1[%d] = %d, want %d", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := s0.BandType[i], int(f.i32()); got != want {
				t.Fatalf("case %d: band_type0[%d] = %d, want %d", ci, i, got, want)
			}
		}
		for i := range 128 {
			if got, want := s1.BandType[i], int(f.i32()); got != want {
				t.Fatalf("case %d: band_type1b[%d] = %d, want %d", ci, i, got, want)
			}
		}
		for k := range 1024 {
			if got, want := math.Float32bits(s0.Coeffs[k]), f.f32bits(); got != want {
				t.Fatalf("case %d post-MS: coeffs0[%d] = %x, want %x", ci, k, got, want)
			}
		}
		for k := range 1024 {
			if got, want := math.Float32bits(s1.Coeffs[k]), f.f32bits(); got != want {
				t.Fatalf("case %d post-MS: coeffs1[%d] = %x, want %x", ci, k, got, want)
			}
		}
	}
	if f.off != len(f.buf) {
		t.Fatalf("fixture: %d bytes left", len(f.buf)-f.off)
	}
}
