// SPDX-License-Identifier: LGPL-2.1-or-later

package coder

import (
	"encoding/binary"
	"math"
	"os"
	"testing"

	"github.com/tphakala/go-aac/internal/mdct"
	"github.com/tphakala/go-aac/internal/window"
)

// Fixtures generated by tools/cquant from the pinned FFmpeg tree: the real
// search_for_quantizers_fast, codebook_trellis_rate and
// quantize_and_encode_band run on a known tonal frame with the Phase 1
// placeholder psy values.

func loadF32(t *testing.T, name string) []float32 {
	t.Helper()
	b, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	out := make([]float32, len(b)/4)
	for i := range out {
		out[i] = math.Float32frombits(binary.LittleEndian.Uint32(b[4*i:]))
	}
	return out
}

func loadI32(t *testing.T, name string) []int32 {
	t.Helper()
	b, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	out := make([]int32, len(b)/4)
	for i := range out {
		out[i] = int32(binary.LittleEndian.Uint32(b[4*i:]))
	}
	return out
}

func loadU8(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// tonalWindowedCoeffs recomputes the fixture's MDCT input in Go: samples
// [2048, 4096) of the gate signal, KBD long window on both halves, MDCT
// scale 32768.
func tonalWindowedCoeffs() []float32 {
	const rate = 44100
	src := make([]float32, 4096)
	for i := range src {
		ts := float64(i) / rate
		src[i] = float32(0.35*math.Sin(2*math.Pi*220*ts) +
			0.25*math.Sin(2*math.Pi*997*ts) +
			0.10*math.Sin(2*math.Pi*3800*ts))
	}
	winbuf := make([]float32, 2048)
	for i := range 1024 {
		winbuf[i] = src[2048+i] * window.KBDLong1024[i]
		winbuf[1024+i] = src[3072+i] * window.KBDLong1024[1023-i]
	}
	coeffs := make([]float32, 1024)
	mdct.New(1024, 32768.0).Transform(coeffs, winbuf)
	return coeffs
}

func TestWindowedMDCTMatchesC(t *testing.T) {
	want := loadF32(t, "fast_in_coeffs.f32")
	got := tonalWindowedCoeffs()
	var peak, maxDiff float64
	for i := range want {
		peak = math.Max(peak, math.Abs(float64(want[i])))
		maxDiff = math.Max(maxDiff, math.Abs(float64(got[i])-float64(want[i])))
	}
	rel := maxDiff / peak
	t.Logf("windowed MDCT: peak %.4g, max abs diff %.4g, rel %.3g", peak, maxDiff, rel)
	if rel > 1e-4 {
		t.Errorf("max diff relative to peak %g exceeds 1e-4", rel)
	}
}
