// SPDX-License-Identifier: LGPL-2.1-or-later

package coder

import (
	"bytes"
	"testing"

	"github.com/tphakala/go-aac/internal/bits"
	"github.com/tphakala/go-aac/internal/tables"
)

// Grouped EIGHT_SHORT fixtures generated by tools/cquant from the pinned
// FFmpeg tree: the real search_for_quantizers_fast, codebook_trellis_rate
// and quantize_and_encode_band run on a castanet-like 8-short-window frame
// with group_len {1,3,0,0,3,0,0,1}. These pin the w*16+g convention on
// real multiple window groups (the Phase 1 fixtures had exactly one
// group, so a wrong stride was invisible until now).

// newShortSCE loads the C's short-block MDCT coefficients into a grouped
// 44.1 kHz EIGHT_SHORT SCE with the fixture's per-window placeholder psy.
func newShortSCE(t *testing.T) (*SingleChannelElement, *[128]PsyBand) {
	t.Helper()
	sce := &SingleChannelElement{}
	sce.ICS.NumWindows = 8
	groupLen := [8]int{1, 3, 0, 0, 3, 0, 0, 1}
	copy(sce.ICS.GroupLen[:], groupLen[:])
	sce.ICS.SwbSizes = tables.SwbSize128[4]
	sce.ICS.SwbOffset = tables.SwbOffset128[4]
	sce.ICS.NumSwb = int(tables.NumSwb128[4])
	copy(sce.Coeffs[:], loadF32(t, "short_in_coeffs.f32"))

	// Per-window placeholder psy with the short cutoff
	// (bandwidth 20000 -> cutoff 20000*2048/8/44100 = 116).
	const cutoff = 116
	psy := &[128]PsyBand{}
	for w := range 8 {
		start := w * 128
		wstart := 0
		for g := range sce.ICS.NumSwb {
			size := int(sce.ICS.SwbSizes[g])
			var energy float32
			if wstart < cutoff {
				for _, v := range sce.Coeffs[start : start+size] {
					energy += v * v
				}
			}
			psy[w*16+g] = PsyBand{Energy: energy, Threshold: energy * 0.001258925}
			start += size
			wstart += size
		}
	}
	return sce, psy
}

func TestSearchForQuantizersFastShortMatchesC(t *testing.T) {
	sce, psy := newShortSCE(t)
	var c Coder
	c.SearchForQuantizersFast(128000, 44100, 1, sce, psy, 120.0)

	wantSf := loadI32(t, "short_fast_sf.i32")
	wantBt := loadI32(t, "short_fast_bt.i32")
	wantZero := loadU8(t, "short_fast_zero.u8")
	mism := 0
	for i := range 128 {
		if int32(sce.SfIdx[i]) != wantSf[i] || int32(sce.BandType[i]) != wantBt[i] ||
			sce.Zeroes[i] != (wantZero[i] != 0) {
			mism++
			if mism <= 10 {
				t.Errorf("slot %d (w %d g %d): got sf=%d bt=%d z=%v, want sf=%d bt=%d z=%d",
					i, i/16, i%16, sce.SfIdx[i], sce.BandType[i], sce.Zeroes[i],
					wantSf[i], wantBt[i], wantZero[i])
			}
		}
	}
	if mism > 0 {
		t.Errorf("%d/128 grouped band decisions differ from C", mism)
	}
}

func TestGroupedTrellisAndSpectraMatchC(t *testing.T) {
	sce, psy := newShortSCE(t)
	var c Coder
	c.SearchForQuantizersFast(128000, 44100, 1, sce, psy, 120.0)

	// adjust_frame_information, grouped subset (aacenc.c:503-531), exactly
	// as the fixture generator ran it.
	maxsfb := 0
	ics := &sce.ICS
	for w := 0; w < ics.NumWindows; w += ics.GroupLen[w] {
		cmaxsfb := ics.NumSwb
		for cmaxsfb > 0 && sce.Zeroes[w*16+cmaxsfb-1] {
			cmaxsfb--
		}
		maxsfb = max(maxsfb, cmaxsfb)
	}
	ics.MaxSfb = maxsfb
	ics.EachBand(ics.MaxSfb, func(w, g, idx int) {
		allZero := true
		for w2 := w; w2 < w+ics.GroupLen[w]; w2++ {
			if !sce.Zeroes[w2*16+g] {
				allZero = false
				break
			}
		}
		sce.Zeroes[idx] = allZero
	})

	wantMisc := loadI32(t, "short_misc.i32")
	if int32(ics.MaxSfb) != wantMisc[0] {
		t.Fatalf("max_sfb %d, want %d", ics.MaxSfb, wantMisc[0])
	}

	pb := bits.NewWriter(make([]byte, 0, 3072))
	for w := 0; w < ics.NumWindows; w += ics.GroupLen[w] {
		c.CodebookTrellisRate(pb, sce, w, ics.GroupLen[w], 120.0)
	}
	// encode_spectral_coeffs (aacenc.c:900-923) over the same bitstream
	for w := 0; w < ics.NumWindows; w += ics.GroupLen[w] {
		start := 0
		for i := range ics.MaxSfb {
			if sce.Zeroes[w*16+i] {
				start += int(ics.SwbSizes[i])
				continue
			}
			for w2 := w; w2 < w+ics.GroupLen[w]; w2++ {
				size := int(ics.SwbSizes[i])
				c.QuantizeAndEncodeBand(pb,
					sce.Coeffs[start+w2*128:start+w2*128+size],
					sce.SfIdx[w*16+i], sce.BandType[w*16+i], 120.0, false)
			}
			start += int(ics.SwbSizes[i])
		}
	}
	if int32(pb.Count()) != wantMisc[1] {
		t.Errorf("bit count %d, want %d", pb.Count(), wantMisc[1])
	}
	got := pb.Flush()
	want := loadU8(t, "short_bits.bin")
	if !bytes.Equal(got, want) {
		limit := min(len(got), len(want))
		firstDiff := -1
		for i := range limit {
			if got[i] != want[i] {
				firstDiff = i
				break
			}
		}
		t.Errorf("grouped section+spectral bytes differ (len %d vs %d, first diff at %d)",
			len(got), len(want), firstDiff)
	}

	wantBt := loadI32(t, "short_bt.i32")
	wantZero := loadU8(t, "short_zero.u8")
	for i := range 128 {
		if int32(sce.BandType[i]) != wantBt[i] || sce.Zeroes[i] != (wantZero[i] != 0) {
			t.Errorf("slot %d: post-trellis bt=%d z=%v, want bt=%d z=%d",
				i, sce.BandType[i], sce.Zeroes[i], wantBt[i], wantZero[i])
		}
	}
}
