// SPDX-License-Identifier: LGPL-2.1-or-later

package coder

import (
	"math"
	"testing"

	"github.com/tphakala/go-aac/internal/bits"
	"github.com/tphakala/go-aac/internal/tables"
)

// Fixture generated by tools/ctns from the pinned FFmpeg tree: the real
// ff_aac_search_for_tns, ff_aac_apply_tns and ff_aac_encode_tns_info run
// on LCG-driven synthetic frames (-ffp-contract=off build). The Go port
// must reproduce every decision, coefficient and post-filter coefficient
// bit-exactly.

type tnsCase struct {
	srIdx   int
	wseq    int
	gl      [8]int
	maxSfb  int
	maLo    int
	maHi    int
	amp     float32
	thrLo   float32
	thrHi   float32
	noiseG  int
	front   [8]int
	nwin    int
	is8     bool
	tnsMaxB func() int
}

// tnsSynthCoeffs mirrors ctns.c:synth_coeffs: MA(ma) smoothing across the
// spectral index (adds of independent noise plus one product; no fusable
// multiply-add, so all builds generate identical inputs).
func tnsSynthCoeffs(l *cnmrLCG, sce *SingleChannelElement, ma int, amp float32) {
	var n [1040]float32
	for i := range n {
		n[i] = 2.0*l.f() - 1.0
	}
	for k := range 1024 {
		acc := float32(0.0)
		for j := 0; j <= ma; j++ {
			acc += n[k+j]
		}
		sce.Coeffs[k] = amp * acc
	}
}

func tnsSynthRetbuf(l *cnmrLCG, sce *SingleChannelElement, is8 bool, front [8]int) {
	tlen, nwin := 2048, 1
	if is8 {
		tlen, nwin = 256, 8
	}
	for w := range nwin {
		ahead, atail := float32(2.0), float32(0.25)
		if front[w] == 0 {
			ahead, atail = 0.25, 2.0
		}
		for t := range tlen {
			a := ahead
			if t >= tlen/2 {
				a = atail
			}
			sce.RetBuf[w*tlen+t] = a * (2.0*l.f() - 1.0)
		}
	}
}

//nolint:gocognit,gocyclo // sequential fixture-format walk
func TestTNSAgainstC(t *testing.T) {
	fr := [8]int{1, 1, 1, 1, 1, 1, 1, 1}
	bk := [8]int{}
	mx := [8]int{1, 0, 1, 0, 0, 1, 0, 1}
	grp := [8]int{1, 3, 0, 0, 3, 0, 0, 1}
	flat := [8]int{1, 1, 1, 1, 1, 1, 1, 1}

	cases := []tnsCase{
		{3, OnlyLongSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, -1, bk, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 0, 0, 12.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 4, 0, 12.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 12, 12, 25.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{3, LongStartSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, -1, bk, 1, false, nil},
		{3, LongStopSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{3, EightShortSequence, grp, 0, 4, 4, 30.0, 0.5, 2.0, -1, mx, 8, true, nil},
		{3, EightShortSequence, flat, 0, 3, 3, 30.0, 0.5, 2.0, -1, mx, 8, true, nil},
		{3, OnlyLongSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, 30, fr, 1, false, nil},
		{3, OnlyLongSequence, flat, 20, 4, 4, 12.0, 0.5, 2.0, -1, fr, 1, false, nil},
		{4, OnlyLongSequence, flat, 0, 4, 4, 12.0, 0.5, 2.0, -1, bk, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 4, 4, 12.0, 1e-6, 1e-5, -1, fr, 1, false, nil},
		{3, OnlyLongSequence, flat, 0, 4, 4, 0.02, 30.0, 90.0, -1, fr, 1, false, nil},
	}

	f := openFixture(t, "tns_search.bin")
	lcg := cnmrLCG(0x1f2e3d4c)
	var cd Coder
	var psy [128]PsyBand

	for ci, tc := range cases {
		var sce SingleChannelElement
		is8 := tc.wseq == EightShortSequence
		sce.ICS.WindowSequence[0] = tc.wseq
		sce.ICS.NumWindows = 1
		if is8 {
			sce.ICS.NumWindows = 8
			sce.ICS.GroupLen = tc.gl
			sce.ICS.SwbSizes = tables.SwbSize128[tc.srIdx]
			sce.ICS.SwbOffset = tables.SwbOffset128[tc.srIdx]
			sce.ICS.NumSwb = int(tables.NumSwb128[tc.srIdx])
			sce.ICS.TnsMaxBands = int(tables.TNSMaxBands128[tc.srIdx])
		} else {
			sce.ICS.GroupLen[0] = 1
			sce.ICS.SwbSizes = tables.SwbSize1024[tc.srIdx]
			sce.ICS.SwbOffset = tables.SwbOffset1024[tc.srIdx]
			sce.ICS.NumSwb = int(tables.NumSwb1024[tc.srIdx])
			sce.ICS.TnsMaxBands = int(tables.TNSMaxBands1024[tc.srIdx])
		}
		sce.ICS.MaxSfb = sce.ICS.NumSwb
		if tc.maxSfb > 0 {
			sce.ICS.MaxSfb = min(tc.maxSfb, sce.ICS.NumSwb)
		}

		tnsSynthCoeffs(&lcg, &sce, tc.maLo, tc.amp)
		if tc.maHi != tc.maLo {
			var n [1040]float32
			for i := range n {
				n[i] = 2.0*lcg.f() - 1.0
			}
			for k := 512; k < 1024; k++ {
				acc := float32(0.0)
				for j := 0; j <= tc.maHi; j++ {
					acc += n[k+j]
				}
				sce.Coeffs[k] = tc.amp * acc
			}
		}
		tnsSynthRetbuf(&lcg, &sce, is8, tc.front)

		for i := range 128 {
			d := float32((tc.thrHi - tc.thrLo) * lcg.f()) // no FMA
			th := tc.thrLo + d
			psy[i].Threshold = th * th
			psy[i].Energy = 100.0 * th * th
			sce.BandType[i] = 0
			sce.Zeroes[i] = false
		}
		if tc.noiseG >= 0 {
			sce.BandType[tc.noiseG] = NoiseBT
		}

		cd.SearchForTNS(tc.srIdx, &sce, &psy)

		// dump_tns comparison
		wantPresent := f.i32() != 0
		if sce.TNS.Present != wantPresent {
			t.Fatalf("case %d: present = %v, want %v", ci, sce.TNS.Present, wantPresent)
		}
		for w := range sce.ICS.NumWindows {
			if got, want := sce.TNS.NFilt[w], int(f.i32()); got != want {
				t.Fatalf("case %d w%d: n_filt = %d, want %d", ci, w, got, want)
			}
			for fi := range 4 {
				if got, want := sce.TNS.Length[w][fi], int(f.i32()); got != want {
					t.Fatalf("case %d w%d f%d: length = %d, want %d", ci, w, fi, got, want)
				}
				if got, want := sce.TNS.Order[w][fi], int(f.i32()); got != want {
					t.Fatalf("case %d w%d f%d: order = %d, want %d", ci, w, fi, got, want)
				}
				if got, want := sce.TNS.Direction[w][fi], int(f.i32()); got != want {
					t.Fatalf("case %d w%d f%d: direction = %d, want %d", ci, w, fi, got, want)
				}
				for o := range TNSMaxOrder {
					if got, want := sce.TNS.CoefIdx[w][fi][o], int(f.i32()); got != want {
						t.Fatalf("case %d w%d f%d o%d: coef_idx = %d, want %d", ci, w, fi, o, got, want)
					}
					want := f.f32()
					got := sce.TNS.Coef[w][fi][o]
					if math.Float32bits(got) != math.Float32bits(want) {
						t.Fatalf("case %d w%d f%d o%d: coef = %x, want %x", ci, w, fi, o,
							math.Float32bits(got), math.Float32bits(want))
					}
				}
			}
		}

		ApplyTNS(&sce)
		for k := range 1024 {
			want := f.f32()
			if math.Float32bits(sce.Coeffs[k]) != math.Float32bits(want) {
				t.Fatalf("case %d coeff %d: %x, want %x", ci, k,
					math.Float32bits(sce.Coeffs[k]), math.Float32bits(want))
			}
		}

		pb := bits.NewWriter(make([]byte, 0, 1024))
		EncodeTNSInfo(pb, &sce)
		wantBits := int(f.i32())
		if pb.Count() != wantBits {
			t.Fatalf("case %d: tns_info bits = %d, want %d", ci, pb.Count(), wantBits)
		}
		payload := pb.Flush()
		for i := range (wantBits + 7) / 8 {
			want := f.u8()
			if payload[i] != want {
				t.Fatalf("case %d: tns_info byte %d = %02x, want %02x", ci, i, payload[i], want)
			}
		}
	}

	// Crafted coef_compress cases: every index outside [4,11]; the writer
	// must emit the 1-bit-shorter form and mutate coef_idx in place
	// exactly like compress_coeffs.
	{
		var sce SingleChannelElement
		sce.ICS.WindowSequence[0] = OnlyLongSequence
		sce.ICS.NumWindows = 1
		sce.TNS.Present = true
		sce.TNS.NFilt[0] = 2
		sce.TNS.Length[0][0], sce.TNS.Order[0][0], sce.TNS.Direction[0][0] = 12, 6, 1
		copy(sce.TNS.CoefIdx[0][0][:6], []int{12, 13, 14, 15, 0, 3})
		sce.TNS.Length[0][1], sce.TNS.Order[0][1], sce.TNS.Direction[0][1] = 12, 6, 0
		copy(sce.TNS.CoefIdx[0][1][:6], []int{2, 1, 12, 15, 3, 0})
		pb := bits.NewWriter(make([]byte, 0, 64))
		EncodeTNSInfo(pb, &sce)
		wantBits := int(f.i32())
		if pb.Count() != wantBits {
			t.Fatalf("compress long: bits = %d, want %d", pb.Count(), wantBits)
		}
		payload := pb.Flush()
		for i := range (wantBits + 7) / 8 {
			if want := f.u8(); payload[i] != want {
				t.Fatalf("compress long: byte %d = %02x, want %02x", i, payload[i], want)
			}
		}
		for f2 := range 2 {
			for i := range 6 {
				if want := int(f.i32()); sce.TNS.CoefIdx[0][f2][i] != want {
					t.Fatalf("compress long: mutated idx[%d][%d] = %d, want %d",
						f2, i, sce.TNS.CoefIdx[0][f2][i], want)
				}
			}
		}
	}
	{
		var sce SingleChannelElement
		sce.ICS.WindowSequence[0] = EightShortSequence
		sce.ICS.NumWindows = 8
		sce.TNS.Present = true
		sce.TNS.NFilt[3] = 1
		sce.TNS.Length[3][0], sce.TNS.Order[3][0], sce.TNS.Direction[3][0] = 11, 7, 1
		copy(sce.TNS.CoefIdx[3][0][:7], []int{15, 14, 13, 12, 1, 2, 3})
		pb := bits.NewWriter(make([]byte, 0, 64))
		EncodeTNSInfo(pb, &sce)
		wantBits := int(f.i32())
		if pb.Count() != wantBits {
			t.Fatalf("compress short: bits = %d, want %d", pb.Count(), wantBits)
		}
		payload := pb.Flush()
		for i := range (wantBits + 7) / 8 {
			if want := f.u8(); payload[i] != want {
				t.Fatalf("compress short: byte %d = %02x, want %02x", i, payload[i], want)
			}
		}
		for i := range 7 {
			if want := int(f.i32()); sce.TNS.CoefIdx[3][0][i] != want {
				t.Fatalf("compress short: mutated idx[%d] = %d, want %d",
					i, sce.TNS.CoefIdx[3][0][i], want)
			}
		}
	}
	f.done()
}
