// SPDX-License-Identifier: LGPL-2.1-or-later

package coder

import (
	"math"
	"testing"

	"github.com/tphakala/go-aac/internal/tables"
)

// Fixture generated by tools/ctwoloop: the real
// search_for_quantizers_twoloop, mark_pns and search_for_pns from the
// pinned tree on LCG-driven synthetic frames (-ffp-contract=off build).

type twoloopCase struct {
	srIdx, rate       int
	short_            bool
	bitrate, channels int
	bitresAlloc       int
	lambda            float32
	pns               bool
	amp               float32
	thrRLo, thrRHi    float32
	sprLo, sprHi      float32
}

func tlSynthFrame(l *cnmrLCG, sce *SingleChannelElement, amp float32) {
	var n [1040]float32
	for i := range n {
		n[i] = 2.0*l.f() - 1.0
	}
	ics := &sce.ICS
	for w := 0; w < ics.NumWindows; w += ics.GroupLen[w] {
		for g := range ics.NumSwb {
			profile := int(l.next() % 5)
			e := [5]float32{0.0, 0.02, 0.6, 4.0, 40.0}[profile]
			for w2 := range ics.GroupLen[w] {
				s0, s1 := int(ics.SwbOffset[g]), int(ics.SwbOffset[g+1])
				for k := s0; k < s1; k++ {
					acc := float32(0.0)
					for j := 0; j <= 3; j++ {
						acc += n[(w+w2)*128+k+j]
					}
					sce.Coeffs[(w+w2)*128+k] = amp * e * acc
				}
			}
		}
	}
}

func tlSynthPsy(l *cnmrLCG, sce *SingleChannelElement, psy *[128]PsyBand,
	thrRLo, thrRHi, sprLo, sprHi float32) {
	ics := &sce.ICS
	for w := range ics.NumWindows {
		for g := range ics.NumSwb {
			b := &psy[w*16+g]
			s0, s1 := int(ics.SwbOffset[g]), int(ics.SwbOffset[g+1])
			e := float32(0.0)
			for k := s0; k < s1; k++ {
				t := float32(sce.Coeffs[w*128+k] * sce.Coeffs[w*128+k])
				e += t
			}
			b.Energy = e
			d := float32((thrRHi - thrRLo) * l.f()) // no FMA
			b.Threshold = e * (thrRLo + d)
			d2 := float32((sprHi - sprLo) * l.f()) // no FMA
			b.Spread = sprLo + d2
		}
	}
}

//nolint:gocognit,gocyclo // sequential fixture-format walk
func TestTwoLoopAgainstC(t *testing.T) {
	cases := []twoloopCase{
		{3, 48000, false, 128000, 1, -1, 120.0, true, 1.0, 0.001, 0.01, 0.4, 2.0},
		{3, 48000, false, 128000, 1, -1, 120.0, false, 1.0, 0.001, 0.01, 0.4, 2.0},
		{3, 48000, false, 32000, 1, -1, 700.0, true, 1.0, 0.02, 0.3, 0.9, 2.0},
		{3, 48000, false, 24000, 1, -1, 2600.0, true, 0.4, 0.05, 0.4, 1.2, 2.0},
		{3, 48000, false, 192000, 1, 6100, 40.0, true, 2.5, 0.0005, 0.004, 0.4, 2.0},
		{4, 44100, true, 128000, 1, -1, 120.0, true, 1.5, 0.002, 0.02, 0.5, 2.0},
		{4, 44100, true, 48000, 1, -1, 900.0, true, 0.8, 0.03, 0.3, 1.0, 2.0},
		{3, 48000, false, 128000, 2, -1, 120.0, true, 1.0, 0.001, 0.01, 0.4, 2.0},
		{3, 48000, false, 96000, 1, 750, 300.0, true, 1.0, 0.01, 0.1, 0.8, 2.0},
		{4, 44100, false, 64000, 1, -1, 450.0, true, 0.15, 0.01, 0.2, 0.9, 2.0},
		{3, 48000, false, 16000, 1, -1, 3000.0, true, 2.0, 5e-5, 5e-4, 1.4, 2.0},
		{4, 44100, true, 24000, 1, -1, 2000.0, true, 3.0, 1e-4, 1e-3, 1.4, 2.0},
		{3, 48000, false, 16000, 1, -1, 3500.0, true, 2.0, 2e-4, 2.05e-4, 1.8, 1.85},
	}

	f := openFixture(t, "twoloop_search.bin")
	lcg := cnmrLCG(0x517cc1b7)
	var cd Coder
	var psy [128]PsyBand

	for ci, tc := range cases {
		var sce SingleChannelElement
		if tc.short_ {
			sce.ICS.WindowSequence[0] = EightShortSequence
			sce.ICS.NumWindows = 8
			sce.ICS.GroupLen = [8]int{1, 3, 0, 0, 3, 0, 0, 1}
			sce.ICS.SwbSizes = tables.SwbSize128[tc.srIdx]
			sce.ICS.SwbOffset = tables.SwbOffset128[tc.srIdx]
			sce.ICS.NumSwb = int(tables.NumSwb128[tc.srIdx])
		} else {
			sce.ICS.WindowSequence[0] = OnlyLongSequence
			sce.ICS.NumWindows = 1
			sce.ICS.GroupLen[0] = 1
			sce.ICS.SwbSizes = tables.SwbSize1024[tc.srIdx]
			sce.ICS.SwbOffset = tables.SwbOffset1024[tc.srIdx]
			sce.ICS.NumSwb = int(tables.NumSwb1024[tc.srIdx])
		}
		sce.ICS.MaxSfb = sce.ICS.NumSwb

		bandwidth := min(tc.rate/2, 20000)

		tlSynthFrame(&lcg, &sce, tc.amp)
		tlSynthPsy(&lcg, &sce, &psy, tc.thrRLo, tc.thrRHi, tc.sprLo, tc.sprHi)

		if tc.pns {
			cd.MarkPNS(tc.rate, bandwidth, &sce, &psy, tc.lambda)
		}
		for i := range 128 {
			want := f.u8() != 0
			if sce.CanPNS[i] != want {
				t.Fatalf("case %d: can_pns[%d] = %v, want %v", ci, i, sce.CanPNS[i], want)
			}
		}
		for i := range 128 {
			want := f.f32()
			if math.Float32bits(sce.PnsEner[i]) != math.Float32bits(want) {
				t.Fatalf("case %d: pns_ener[%d] = %x, want %x", ci, i,
					math.Float32bits(sce.PnsEner[i]), math.Float32bits(want))
			}
		}

		cd.SearchForQuantizersTwoLoop(tc.bitrate, tc.rate, tc.channels,
			tc.bitresAlloc, bandwidth, tc.pns, &sce, &psy, tc.lambda)

		for i := range 128 {
			if want := int(f.i32()); sce.SfIdx[i] != want {
				t.Fatalf("case %d: sf_idx[%d] = %d, want %d", ci, i, sce.SfIdx[i], want)
			}
		}
		for i := range 128 {
			if want := int(f.i32()); sce.BandType[i] != want {
				t.Fatalf("case %d: band_type[%d] = %d, want %d", ci, i, sce.BandType[i], want)
			}
		}
		for i := range 128 {
			want := f.u8() != 0
			if sce.Zeroes[i] != want {
				t.Fatalf("case %d: zeroes[%d] = %v, want %v", ci, i, sce.Zeroes[i], want)
			}
		}

		if tc.pns {
			cd.RandomState = 0x1f2e3d4c
			cd.SearchForPNS(tc.rate, bandwidth, &sce, &psy, tc.lambda)
			if want := f.i32(); cd.RandomState != want {
				t.Fatalf("case %d: random_state = %08x, want %08x", ci,
					uint32(cd.RandomState), uint32(want))
			}
			for i := range 128 {
				if want := int(f.i32()); sce.SfIdx[i] != want {
					t.Fatalf("case %d post-pns: sf_idx[%d] = %d, want %d", ci, i, sce.SfIdx[i], want)
				}
			}
			for i := range 128 {
				if want := int(f.i32()); sce.BandType[i] != want {
					t.Fatalf("case %d post-pns: band_type[%d] = %d, want %d", ci, i, sce.BandType[i], want)
				}
			}
			for i := range 128 {
				want := f.u8() != 0
				if sce.Zeroes[i] != want {
					t.Fatalf("case %d post-pns: zeroes[%d] = %v, want %v", ci, i, sce.Zeroes[i], want)
				}
			}
			for i := range 128 {
				want := f.f32()
				if math.Float32bits(sce.PnsEner[i]) != math.Float32bits(want) {
					t.Fatalf("case %d post-pns: pns_ener[%d] = %x, want %x", ci, i,
						math.Float32bits(sce.PnsEner[i]), math.Float32bits(want))
				}
			}
		}
	}
	f.done()
}
